### ISSUE TITLE
Map looks so noisy in Gazebo environments

### ISSUE THREAD

**Issue by kotakondo** [hku-mars/SUPER#10]
![Image](https://github.com/user-attachments/assets/41b86ee6-8991-4707-b5f8-18a9baafeb51)

Hi when I run the simulation in Gazebo environments (using Livox scan laser simulater to generate pointcloud), the occupancy map looks very noisy. I am using the click_map demo config parameters, could you please let me know how to fix this issue and/or any suggestions on how to use SUPER in gazebo environments?? thanks!

**Comment by RENyunfan** [comment]
Could I get a rosbag for this? I suspect the issue might be due to the simulation adding noise to the point clouds. If that’s the case, you may need to enable raycasting in `rog_map` and adjust some parameters to filter out the sensor noise.

https://github.com/hku-mars/SUPER/blob/master/super_planner/config/click_smooth_ros1.yaml#L168

```yaml
 # Probabilistc update
  raycasting:
    enable: true # HERE
    batch_update_size: 1
    local_update_box: [ 100,100,5 ]
    ray_range: [0.5, 15 ]

    p_min: 0.12
    p_miss: 0.45
    p_free: 0.455
    p_occ: 0.85
    p_hit: 0.9
    p_max: 0.98
    # The threshold of a non-occupied inf map grid to be considered as free. [0.0-1.0]
    # for counter map, if each cell contains N cells in prob map, then only when
    # N_unk > N * unk_thresh cells are unknown, the cell will be considered as unknown.
    # example: 1) if unk_thresh is set 0.0, then once at least one cell in prob map is unknown,
    #             the cell will be considered as unknown.
    #         2) if unk_thresh is set to 1.0, then only all cells in prob map are unknown,
    #             the cell will be considered as unknown.
    # in all, 1.0 is more aggressive while 0.0 is more conservative.
    unk_thresh: 1.0

```
