### ISSUE TITLE
the mpc topic "/planning_cmd/poly_traj" is empty,But I have traj

### ISSUE THREAD

**Issue by hcws** [hku-mars/SUPER#25]
Here is the topic content:
```

header: 
  seq: 985
  stamp: 
    secs: 97
    nsecs: 841000000
  frame_id: "world"
trajectory_id: 0
type: 1
piece_num_yaw: 0
piece_num_pos: 0
order_pos: 0
order_yaw: 0
start_WT_yaw: 
  secs: 0
  nsecs:         0
yaw: 0.0
yaw_rate: 0.0
coef_yaw: []
time_yaw: []
start_WT_pos: 
  secs: 97
  nsecs: 242000000
coef_pos_x: []
coef_pos_y: []
coef_pos_z: []
time_pos: []
debug_info: ''
---
^Cheader: 
  seq: 986
  stamp: 
    secs: 97
    nsecs: 851000000
  frame_id: "world"
trajectory_id: 0
type: 1
piece_num_yaw: 0
piece_num_pos: 0
order_pos: 0
order_yaw: 0
start_WT_yaw: 
  secs: 0
  nsecs:         0
yaw: 0.0
yaw_rate: 0.0
coef_yaw: []
time_yaw: []
start_WT_pos: 
  secs: 97
  nsecs: 242000000
coef_pos_x: []
coef_pos_y: []
coef_pos_z: []
time_pos: []
debug_info: ''
---

```
