### ISSUE TITLE
I often encounter the problem of trajectory optimization failure in the PX4 simulation environment. How can I modify the following parameters

### ISSUE THREAD

**Issue by hcws** [hku-mars/SUPER#27]
```
traj_opt:
  switch:
    save_log_en: false
    print_optimizer_log: false

  boundary:
    max_vel: 5.0
    max_acc: 5.0
    max_jerk: 120.0
    max_omg: 2.5
    max_acc_thr: 20.0
    min_acc_thr: 6.0
    penna_margin: 0.05
exp_traj:
    # 1 for xi 2 for pos
    pos_constraint_type: 1
    energy_cost_type: 4
    block_energy_cost: false
    opt_accuracy: 5.0e-6
    scale_factor: 1.0
    integral_reso: 15
    smooth_eps: 0.01
    penna_t: 12000.0
    penna_pos: 5.0e+6
    penna_vel: 5.0e+5
    penna_acc: 5.0e+5
    penna_jerk: -5.0e+5
    penna_attract: 1.0e+3
    penna_omg:  5.0e+5
    penna_thr: 1.0e+5

  backup_traj:
    uniform_time_en: true
    pos_constraint_type: 1
    piece_num: 2
    energy_cost_type: 4
    block_energy_cost: true
    opt_accuracy: 1.0e-6
    scale_factor: 1.0
    integral_reso: 12
    smooth_eps: 0.01
    penna_t: 1200.0
    penna_ts: 1.0e+5
    penna_pos: 1.0e+6
    penna_vel: 1.0e+5
    penna_acc: 1.0e+5
    penna_jerk: -1.0e+5
    penna_omg: 1.0e+5
    penna_max_acc_thr: 1.0e+5
    penna_min_acc_thr: 1.0e+5
``` 
Especially：

```
 boundary:
    max_vel: 5.0
    max_acc: 5.0
    max_jerk: 120.0
    max_omg: 2.5
    max_acc_thr: 20.0
    min_acc_thr: 6.0
    penna_margin: 0.05
```

**Comment by RENyunfan** [comment]
Please provide additional details, such as a screen recording, PCD map, and ROSbag, to help me offer suggestions for parameter tuning.

**Comment by hcws** [comment]
**I want to Go through a big obstacle**
Here is the warning log:
```
^C -- [ExpOpt] Opt finish, with iter num: 12
        Energy: 833.232662340742536
        Pos: 3.690747458705438
        Vel: 0.000000000000000
        Acc: 29.978393650214869
        Jerk: 0.000000000000000
        Attract: 0.000000000000000
        Omg: 0.000000000000000
        Thr: 60.638599232201116
        Optimized Time: 4.751512164881737
 -- [ExpOpt] Opt finish, with iter num: 12
        Energy: 833.232662340742536
        Pos: 3.690747458705438
        Vel: 0.000000000000000
        Acc: 29.978393650214869
        Jerk: 0.000000000000000
        Attract: 0.000000000000000
        Omg: 0.000000000000000
        Thr: 60.638599232201116
        Optimized Time: 4.751512164881737
[WARN] [1750126316.391129644, 268.533000000]:  -- [ExpOpt] Opt failed, Omg or thr or Pos violation.
 -- [MINCO] TrajOpt failed, (unknown)
 -- [SUPER] Minco exp_traj opt failed.
[WARN] [1750126316.391295808, 268.533000000]:  -- [SUPER] OptimizationExpTrajInPolytopes for new path failed
[WARN] [1750126316.391307919, 268.533000000]:  -- [SUPER] in [ReplanOnce]: GenerateExpTrajectory failed, force return
```
Here is the param : 
```
fsm:
  click_goal_en: true
  click_goal_topic: "/goal"
  click_height: 10
  click_yaw_en: true
  replan_rate: 15.0
  cmd_topic: "/planning/pos_cmd"
  mpc_cmd_topic: "/planning_cmd/poly_traj"
  timer_en: true

super_planner:
  backup_traj_en: true
  detailed_log_en: true
  visualization_en: true
  use_fov_cut: false
  print_log: false
  visual_process: false
  frontend_in_known_free: false
  goal_yaw_en: true
  goal_vel_en: false
  corridor_bound_dis: 3.0
  corridor_line_max_length: 3
  safe_corridor_line_max_length: 999
  iris_iter_num: 2
  obs_skip_num: 2
  replan_forward_dt: 0.4
  planning_horizon: 30.0
  sensing_horizon: -1
  receding_dis: 15.0
  robot_r: 0.2
  yaw_dot_max: 3.0
  # Yaw mode: 1 heading to velocity, 2 heading to goal
  yaw_mode: 1
  mpc_horizon: 15


traj_opt:
  switch:
    save_log_en: true
    print_optimizer_log: true

  boundary:
    max_vel: 8
    max_acc: 6.0
    max_jerk: 80.0
    max_omg: 2
    max_acc_thr: 10.0
    min_acc_thr: 6.0
    penna_margin: 0.05

  exp_traj:
    # 1 for xi 2 for pos
    pos_constraint_type: 1
    energy_cost_type: 4
    block_energy_cost: false
    opt_accuracy: 5.0e-6
    scale_factor: 1.0
    integral_reso: 15
    smooth_eps: 0.01
    penna_t: 12000.0
    penna_pos: 5.0e+6
    penna_vel: 5.0e+5
    penna_acc: 5.0e+5
    penna_jerk: -5.0e+5
    penna_attract: 1.0e+3
    penna_omg:  5.0e+5
    penna_thr: 1.0e+5

  backup_traj:
    uniform_time_en: true
    pos_constraint_type: 1
    piece_num: 2
    energy_cost_type: 4
    block_energy_cost: true
    opt_accuracy: 1.0e-6
    scale_factor: 1.0
    integral_reso: 12
    smooth_eps: 0.01
    penna_t: 1200.0
    penna_ts: 1.0e+5
    penna_pos: 1.0e+6
    penna_vel: 1.0e+5
    penna_acc: 1.0e+5
    penna_jerk: -1.0e+5
    penna_omg: 1.0e+5
    penna_thr: 1.0e+5

  flatness:
    mass: 1.64
    dh: 0.35
    dv: 0.35
    cp: 0.001
    v_eps: 0.0001
    grav: 9.81


astar:
  map_voxel_num: [ 1000, 1000, 150 ]
  visual_process: false
  allow_diag: true
  # 0 DIAG; 1 MANHATTAN; 2 EUCLIDEAN
  heu_type: 2
  debug_visualization_en: false


rog_map:
  resolution: 0.5
  inflation_resolution: 1
  inflation_step: 2
  unk_inflation_en: false
  unk_inflation_step: 1
  map_size: [ 100,100,15 ]
  # If the map rolling is disable, the map origin [m] should be set.
  fix_map_origin: [ 0,0,5 ]
  frontier_extraction_en: false

  # Virtual ceil and ground
  virtual_ceil_height: 13
  virtual_ground_height: 0.1

  load_pcd_en: false

  map_sliding:
    enable: true
    # The minimum distance [m] to slide the map.
    threshold: 1

  esdf:
    enable: false
    resolution: 0.1
    # The range of esdf around the odom [m].
    local_update_box: [ 5,5,3 ]

  # If [enable = true], the ROG-Map will actively take ros topic as input.
  #  else user should call function [updateMap] to update the map.
  ros_callback:
    enable: true
    cloud_topic: "/cloud_registered"
    odom_topic: "/mavros/local_position/odom"
    odom_timeout: 2.0


  visualization:
    enable: true
    # when enabled, use rqt_reconfigure to change the visualization parameters.
    use_dynamic_reconfigure: false
    # The rate of visualization [Hz], if set to 0, the visualization will not be triggered by frame.
    time_rate: 2
    # The frame rate of visualization [Hz], if set to 0, the visualization will not be triggered by frame.
    frame_rate: 0
    # visualization range along the odom [m].
    range: [ 120, 120,15 ]
    frame_id: "world"
    pub_unknown_map_en: false

  # Intensity filter for input point cloud. If the point intensity is less than this value,
  # it will be ignored (to avoid noise like dusk).
  intensity_thresh: -10
  # The temporal downsample rate for input point cloud.
  #  e.g. if set to k, the point cloud will be downsampled to 1/k.
  point_filt_num: 1

  # Probabilistc update
  raycasting:
    # if disable, the map will only maintain occupied information, and all other grid
    # will be considered as unknown.
    enable: false
    batch_update_size: 1
    local_update_box: [ 100,100,5 ]
    # The range of raycasting [m].
    ray_range: [0.5, 100 ]

    p_min: 0.12
    p_miss: 0.49
    p_free: 0.499
    p_occ: 0.85
    p_hit: 0.9
    p_max: 0.98
    # The threshold of a non-occupied inf map grid to be considered as free. [0.0-1.0]
    # for counter map, if each cell contains N cells in prob map, then only when
    # N_unk > N * unk_thresh cells are unknown, the cell will be considered as unknown.
    # example: 1) if unk_thresh is set 0.0, then once at least one cell in prob map is unknown,
    #             the cell will be considered as unknown.
    #         2) if unk_thresh is set to 1.0, then only all cells in prob map are unknown,
    #             the cell will be considered as unknown.
    # in all, 1.0 is more aggressive while 0.0 is more conservative.
    unk_thresh: 1.0
```
And here is the obstacle : 

![Image](https://github.com/user-attachments/assets/8ca05f89-93e6-44f8-9fa1-952d002db899)
