### ISSUE TITLE
How it applies to automated trolleys

### ISSUE THREAD

**Issue by cyrusliu1984** [hku-mars/SUPER#29]
I am trying to apply SUPER to an unmanned cart, I have modified the relevant height setting parameters and reduced the movement speed, but it still has problems with obstacle avoidance, I would like to ask the author how to set it up so that it recognizes obstacles on the ground and how to set the volume parameters of the cart.

————————————————————————————————————————————————————————Here are my parameter settings：
```
fsm:
  click_goal_en: true
  click_goal_topic: "/goal"
  click_height: 0.1
  click_yaw_en: true
  replan_rate: 15.0
  cmd_topic: "/planning/pos_cmd"
  mpc_cmd_topic: "/planning_cmd/poly_traj"
  timer_en: true

super_planner:
  backup_traj_en: true
  detailed_log_en: true
  visualization_en: true
  use_fov_cut: false
  print_log: true
  visual_process: false
  frontend_in_known_free: false
  goal_yaw_en: true
  goal_vel_en: false
  corridor_bound_dis: 1.0
  corridor_line_max_length: 1.2
  safe_corridor_line_max_length: 5.0
  iris_iter_num: 2
  obs_skip_num: 2
  replan_forward_dt: 0.1
  planning_horizon: 7.0
  sensing_horizon: -1
  receding_dis: 4.0
  robot_r: 0.3
  yaw_dot_max: 3.0
  # Yaw mode: 1 heading to velocity, 2 heading to goal
  yaw_mode: 2
  mpc_horizon: 15


traj_opt:
  switch:
    save_log_en: false
    print_optimizer_log: false

  # 在控制的最大限度上-0.2
  boundary:
    max_vel: 0.3
    max_acc: 1.2
    max_jerk: 10.0
    max_omg: 1.2
    max_acc_thr: 10.0
    min_acc_thr: 1.0
    penna_margin: 0.05

  exp_traj:
    # 1 for xi 2 for pos
    pos_constraint_type: 1
    energy_cost_type: 4
    block_energy_cost: false
    opt_accuracy: 5.0e-6
    scale_factor: 1.0
    integral_reso: 15
    smooth_eps: 0.01
    penna_t: 12000.0
    penna_pos: 5.0e+6
    penna_vel: 5.0e+5
    penna_acc: 5.0e+5
    penna_jerk: -5.0e+5
    penna_attract: 1.0e+3
    penna_omg:  5.0e+5
    penna_thr: 1.0e+5

  backup_traj:
    uniform_time_en: true
    pos_constraint_type: 2
    piece_num: 2
    energy_cost_type: 4
    block_energy_cost: true
    opt_accuracy: 1.0e-6
    scale_factor: 1.0
    integral_reso: 12
    smooth_eps: 0.01
    penna_t: 1200.0
    penna_ts: 1.0e+5
    penna_pos: 1.0e+6
    penna_vel: 1.0e+5
    penna_acc: 1.0e+5
    penna_jerk: -1.0e+5
    penna_omg: 1.0e+5
    penna_thr: 1.0e+5

  flatness:
    # 机器人的质量
    mass: 500
    # 水平方向上的阻尼系数，模拟机器人在水平运动中的能量损耗
    dh: 0.01
    # 垂直方向上的阻尼系数
    dv: 1000
    # 空气阻力系数
    cp: 0.001
    # 速度的最小阈值，用于避免计算中的数值不稳定问题
    v_eps: 0.0001
    grav: 9.81

astar:
  map_voxel_num: [ 800, 800, 2]
  visual_process: false
  allow_diag: true
  # 0 DIAG; 1 MANHATTAN; 2 EUCLIDEAN
  heu_type: 2
  debug_visualization_en: false


rog_map:
  resolution: 0.05
  inflation_resolution: 0.1
  inflation_step: 2
  unk_inflation_en: false
  unk_inflation_step: 1
  map_size: [ 50,50,2 ]
  # If the map rolling is disable, the map origin [m] should be set.
  fix_map_origin: [ 0,0,0.45 ]
  frontier_extraction_en: false

  # Virtual ceil and ground
  virtual_ceil_height: 3.5
  virtual_ground_height: 0.0

  load_pcd_en: false

  map_sliding:
    enable: true
    # The minimum distance [m] to slide the map.
    threshold: 0.3

  esdf:
    enable: false
    resolution: 0.1
    # The range of esdf around the odom [m].
    local_update_box: [ 5,5,3 ]

  # If [enable = true], the ROG-Map will actively take ros topic as input.
  #  else user should call function [updateMap] to update the map.
  ros_callback:
    enable: true
    cloud_topic: "/cloud_registered"
    # odom_topic: "/aft_pgo_odom"
    odom_topic: "/Odometry"
    odom_timeout: 2.0


  visualization:
    enable: true
    # when enabled, use rqt_reconfigure to change the visualization parameters.
    use_dynamic_reconfigure: false
    # The rate of visualization [Hz], if set to 0, the visualization will not be triggered by frame.
    time_rate: 2
    # The frame rate of visualization [Hz], if set to 0, the visualization will not be triggered by frame.
    frame_rate: 0
    # visualization range along the odom [m].
    range: [ 15, 15,5 ]
    frame_id: "odom"
    pub_unknown_map_en: false

  # Intensity filter for input point cloud. If the point intensity is less than this value,
  # it will be ignored (to avoid noise like dusk).
  intensity_thresh: -10
  # The temporal downsample rate for input point cloud.
  #  e.g. if set to k, the point cloud will be downsampled to 1/k.
  point_filt_num: 1

  # Probabilistc update
  raycasting:
    # if disable, the map will only maintain occupied information, and all other grid
    # will be considered as unknown.
    enable: false
    batch_update_size: 1
    local_update_box: [ 20,20,5]
    # The range of raycasting [m].
    ray_range: [0.5, 25 ]

    p_min: 0.12
    # decrease the p_miss to reduce the artifacts left by the moving objects
    p_miss: 0.3 # Consider reducing this to, for example, 0.4  
    p_free: 0.4 # Consider reducing this to, for example, 0.45  
    p_occ: 0.85
    p_hit: 0.9
    p_max: 0.98
    # The threshold of a non-occupied inf map grid to be considered as free. [0.0-1.0]
    # for counter map, if each cell contains N cells in prob map, then only when
    # N_unk > N * unk_thresh cells are unknown, the cell will be considered as unknown.
    # example: 1) if unk_thresh is set 0.0, then once at least one cell in prob map is unknown,
    #             the cell will be considered as unknown.
    #         2) if unk_thresh is set to 1.0, then only all cells in prob map are unknown,
    #             the cell will be considered as unknown.
    # in all, 1.0 is more aggressive while 0.0 is more conservative.
    unk_thresh: 1.0



```

—————————————————————————————————————————————————————————————————
Issue 1: Unable to detect objects on the ground, red boxes are in the world coordinate system, purple boxes are boxes on the ground and black boxes are ground layers that cannot be recognized as obstacles。

issue 2: How can I modify the parameters to fit the physical volume of the cart, currently it looks like the algorithm simply thinks my radar is floating in the air.

![Image](https://github.com/user-attachments/assets/58119369-3ba4-4724-8ec4-61e8a8e7051e)

![Image](https://github.com/user-attachments/assets/72d804d6-dd55-4f11-9513-d65640cea6e0)

![Image](https://github.com/user-attachments/assets/697bd026-ea2a-4e0d-8642-874afbd79f24)
![Image](https://github.com/user-attachments/assets/20298086-0dfe-41a0-8186-bb66a8814415)
