### ISSUE TITLE
The raycasting part doesn't work.

### ISSUE THREAD

**Issue by cyrusliu1984** [hku-mars/SUPER#30]
When I turned on the raycasting parameter I realized that it didn't work, moving obstacle objects were not filtered.

**Comment by RENyunfan** [comment]
Consider adjusting the probability update parameters to improve performance, such as reducing `p_miss`. For example:

```yaml
p_min: 0.12
p_miss: 0.3
p_free: 0.499
p_occ: 0.85
p_hit: 0.86
p_max: 0.99
```
