### ISSUE TITLE
Why does the planned trajectory pass through the expansion point cloud？

### ISSUE THREAD

**Issue by hcws** [hku-mars/SUPER#32]
![Image](https://github.com/user-attachments/assets/9837bf15-5984-4fea-907d-7dc4abc8acd5)
and this is my param 
```
astar:
  map_voxel_num: [ 500, 500, 100 ]
  visual_process: false
  allow_diag: true
  # 0 DIAG; 1 MANHATTAN; 2 EUCLIDEAN
  heu_type: 2
  debug_visualization_en: false


rog_map:
  resolution: 0.5
  inflation_resolution: 1.0
  inflation_step: 2
  unk_inflation_en: false
  unk_inflation_step: 1
  map_size: [ 80,80,15 ]
  # If the map rolling is disable, the map origin [m] should be set.
  fix_map_origin: [ 0,0,10 ]
  frontier_extraction_en: false
```

click_height is 10m,why planned traj is blew 10m

![Image](https://github.com/user-attachments/assets/786ed5a0-6002-4857-a022-9be7fdbdc268)
