### ISSUE TITLE
Problem with Path Height Behavior in Trajectory Planning

### ISSUE THREAD

**Issue by Liansheng-Wang** [hku-mars/SUPER#7]
First of all, thank you for this excellent open-source work.

During my practical testing, I noticed that even though both the start and goal heights of the drone are set to 1.0m, the planner's trajectory tends to rise and stays around 1.5m in the middle. I also observed that there are no obstacles in the lower space.

I am unable to locate where this constraint has been added in the code, and I would appreciate it if you could help me understand this. Thank you very much!

**Comment by RENyunfan** [comment]
Apologies for the unclear documentation. You can find details about this parameter in the configuration file here: [[click_smooth_ros1.yaml](https://github.com/hku-mars/SUPER/blob/master/super_planner/config/click_smooth_ros1.yaml#L4)](https://github.com/hku-mars/SUPER/blob/master/super_planner/config/click_smooth_ros1.yaml#L4).

```yaml 
fsm:
  click_goal_en: true
  click_goal_topic: "/goal"
  click_height: 1.5 # here!!!
  click_yaw_en: true
  replan_rate: 15.0
  cmd_topic: "/planning/pos_cmd"
  mpc_cmd_topic: "/planning_cmd/poly_traj"
  timer_en: true
```

If click_height is set to a value greater than -5 (as shown in the code [[here](https://github.com/hku-mars/SUPER/blob/b13e96ae30f5cfd72d46eccd8ada2c71d4db9531/super_planner/src/super_core/fsm.cpp#L187)](https://github.com/hku-mars/SUPER/blob/b13e96ae30f5cfd72d46eccd8ada2c71d4db9531/super_planner/src/super_core/fsm.cpp#L187)), any input goal will be overridden to use the specified `click_height value`, which is `1.5` in this example.

This parameter is designed to simplify interaction within RViz. If you'd like to use a goal with a custom height, you can disable this feature by setting the parameter to a value less than `-5`(e.g., `-999`).
